services:
  survivor:
    build:
      context: .
      dockerfile: Dockerfile
    image: survivor:latest
    container_name: survivor
    ports:
      - "127.0.0.1:5000:80"
    restart: unless-stopped
